config/routes.rb
Trunkit::Application.routes.draw do
  get 'learn_more/learn_trunkit'

  get 'learn_more/learn_trunksale'

  get 'learntrunksale/learntrunksale'

  get 'learn_trunkit/learn_trunkit'

  root to: "contents#index"

  # Catalog
  get "stream"                    => "stream#index",     as: :stream
  get "stream/following"          => "stream#following", as: :stream_following
  get "stream/category/:category" => "stream#index",     as: :stream_category

  resources :favorites, only: [:index, :create]

  resources :items do
    put 'support',   on: :member
    put 'unsupport', on: :member

    resources :declinations, only: [:index, :update], controller: "item_declinations"
    resources :notifications, only: [:create], controller: "item_notifications"

    resources :photos, controller: "item_photos" do
      put "reorder", on: :collection
    end
  end

  resources :brands, only: [:index, :create]
  resources :categories, only: [:index]
  resources :categories, only: [:index]

  resources :boutiques, :brands, only: [:show] do
    get 'search',   on: :collection
    put 'follow',   on: :member
    put 'unfollow', on: :member
  end

  # Product discovery
  resource :discover, controller: 'discover' do
    get 'q' => 'discover#create', as: :search
  end

  # Checkout and Shopping Cart
  resource :cart do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  namespace :checkout do
    resources :shipping_addresses do
      put "select", on: :member
    end

    resource :delivery_options, :payment_method, :order
  end

  # User information
  resource  :user, only: [:update] do
    get "settings"
  end

  resources :addresses

  # Boutique Management Interfaces
  resources :notifications, :customer_orders, only: [:index]
  resources :customer_orders
  

  scope("order_items/:id", as: :order_item) do
    resource :cancellation, only: [:new, :create], controller: "order_item_cancellations"
    put "complete" => "order_items#complete", as: :complete
  end

  # Boutique Transfers management
  namespace :payments do
    resource  :company, controller: "company"
  end

  # Session Management
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Administrative Interfaces
  resources :shipping_events, only: [:create]

  namespace :admin do
    resources :boutiques
    resources :brands, :categories, :customer_orders

    resources :items do
      put :approve, :unapprove, on: :member
      get :pending_approval,    on: :collection

      resources :sizes,  controller: "item_sizes"
      resources :photos, controller: "item_photos"
    end

    resources :users, except: [:show] do
      post "welcome"    => "users#welcome"
      put  "masquerade" => "users#masquerade"
    end
  end

  get "admin" => redirect("/admin/customer_orders")

  post "boutique_sign_up" => "boutique_sign_up#create"

  # Catch-all, generic routing
  get "*path" => "contents#show"
end

app/views/notifier/boutique_signup.text.erb
Name: <%= @params[:name] %>
Email: <%= @params[:email] %>
Phone: <%= @params[:phone] %>
Store Name: <%= @params[:store_name] %>
City: <%= @params[:city] %>
State: <%= @params[:state] %>
Rep Name: <%= @params[:rep_name] %>

app/views/notifier/cart_item_cancellation.html.erb
<%= @cart_item.item.name %> has been cancelled
<%= @message %>

app/views/notifier/cart_item_cancellation.text.erb
<%= @cart_item.item.name %> has been cancelled
<%= @message %>

app/views/notifier/item_added.html.erb
<p><%= @user.name %> from <%= @item.boutique.name %> submitted the following item:</p>
<% if @item.list_on_trunksale == 2 %>
	<p><%= @item.boutique.name %> WOULD like this item listed on the Trunksale</p>
<% else %>
	<p><%= @item.boutique.name %> WOULD NOT like this item listed on the Trunksale</p>
<% end %>

<p>
	Boutique Name: <%= @item.boutique.name %>
</p>

<p>
	Item Name: <%= @item.name %>
</p>

<p>
	Description: <%= @item.description %>
	<br>
	Fit: <%= @item.fit %>
	<br>
	Material: <%= @item.construction %>
	<br>
	Brand: <%= @item.brand.name %>
	<br>
	Category: <%= @item.primary_category.name %>
	<br>
	Sub Category: <%= @item.secondary_category.name %>
	<br>
	Price: <%= @item.price %>
	<br>
	<% if @item.list_on_trunksale == 2 %>
		Base Price: <%= @item.discount_amount * 1.08 %>
	<% end %>
	<br>
	Sizes: <%= @item.sizes %>
</p>

<p>
	Photos: <%= render(partial: "items/photo", collection: @item.photos, as: :photo) %>
</p>

app/views/notifier/item_restocked.html.erb
<html>
<body>
  <p>Hi <%= @user.name %></p>

  <p><%= @item.name %> by <% @item.brand.name %> is now back in stock. <%= link_to("Click here", search_discover_path(q: @item.name)) %> to check it out.</p>

  <table>
    <tr>
      <td>
        <%= image_tag(@item.primary_photo.url.stream) %>
      </td>

      <td>
        <table>
          <%= content_tag(:tr, content_tag(:td, @item.name)) %>
          <%= content_tag(:tr, content_tag(:td, @item.brand.name)) %>
          <%= content_tag(:tr, content_tag(:td, number_to_currency(@item.price, precision: 0))) %>

          <%= content_tag(:tr) do %>
            <td>
              <p>
                <span>ABOUT THE CLOTHES:</span><br>
                <%= markdown(@item.description) %>
              </p>
            </td>
          <% end if @item.description.present? %>

          <%= content_tag(:tr) do %>
            <td>
              <p>
                <span>HOW DO THEY FIT?</span><br>
                <%= markdown(@item.fit) %>
              </p>
            </td>
          <% end if @item.fit.present? %>

          <%= content_tag(:tr) do %>
            <td>
              <p>
                <span>WHAT ARE THE CLOTHES MADE OF?</span><br>
                <%= markdown(@item.construction) %>
              </p>
            </td>
          <% end if @item.construction.present? %>
        </table>
      </td>
  </table>
</body>
</html>

app/views/notifier/welcome_boutique.html.erb
<p>Hi <%= @user.first_name %>,</p>

<p>We’d like to be the first to welcome you to Trunkit, the place where you can collaborate with other boutiques to maximize the success of your inventory. We’re so excited to introduce you to the exclusive group of retailers who you will be working with.</p>

<p>We know that your time is best spent helping your customers, so we’ve already gone ahead and created an account for you. The only thing left to do is to click the link below to create your password.</p>

<p><%= link_to 'Change my password', edit_password_url(@user, reset_password_token: @token) %></p>

<p>Here are a few tips to get the most out of Trunkit:</p>

<ul>
  <li>Curate inventory your customers will love. By offering your customers additional inventory options, you can insure they always leave happy and shop <%= @user.parent.name %> again and again.</li>
  <li>Supply a few items to get started. When certain inventory isn’t selling well in your store, give another boutique the opportunity to sell that inventory to their customers. It’s a win win :)</li>
  <li>Succeed by collaborating. We’ve chosen you to be one of the first members on Trunkit because we want you to be a trendsetter for other boutiques. By actively curating and supplying inventory, shipping orders on time, and keeping quantity of listed inventory up-to-date, your actions will set the tone for all future boutiques that use the service.</li>

<p>Please feel free to contact the Team@Trunkit.com if you have any additional questions or would like to setup a personal lesson on how to use Trunkit. For more general video tutorials visit trunkit.zendesk.com.</p>

<p>Thanks for joining and congrats on becoming a Trunkit boutique member!</p>

<p>Sam, Max &amp; the Trunkit Team</p>

app/views/notifier/welcome_boutique.text.erb
Hi <%= @user.first_name %>,

We’d like to be the first to welcome you to Trunkit, the place where you can collaborate with other boutiques to maximize the success of your inventory. We’re so excited to introduce you to the exclusive group of retailers who you will be working with.

We know that your time is best spent helping your customers, so we’ve already gone ahead and created an account for you. The only thing left to do is to click the link below to create your password.

<%= edit_password_url(@user, reset_password_token: @token) %>

Here are a few tips to get the most out of Trunkit:

- Curate inventory your customers will love. By offering your customers additional inventory options, you can insure they always leave happy and shop <%= @user.parent.name %> again and again.
- Supply a few items to get started. When certain inventory isn’t selling well in your store, give another boutique the opportunity to sell that inventory to their customers. It’s a win win :)
- Succeed by collaborating. We’ve chosen you to be one of the first members on Trunkit because we want you to be a trendsetter for other boutiques. By actively curating and supplying inventory, shipping orders on time, and keeping quantity of listed inventory up-to-date, your actions will set the tone for all future boutiques that use the service.

Please feel free to contact the Team@Trunkit.com if you have any additional questions or would like to setup a personal lesson on how to use Trunkit. For more general video tutorials visit trunkit.zendesk.com.

Thanks for joining and congrats on becoming a Trunkit boutique member!

Sam, Max & the Trunkit Team

app/views/notifier/welcome_email.html.erb
<h3>HI <%= @user.first_name %>,</h3>

<p>We’re so excited that you’ve signed up to become a member of Trunkit and we hope you had a great first experience using the site. Your favorite fashion boutiques can now work together to bring you the best customer experience while offering you additional inventory that you’ll love. <%= "In order to sign in again using the same account we need you to create a password by visiting the link below." if @user.provider.blank? %></p>

<%= content_tag(:p, link_to("Change My Password", settings_user_url)) if @user.provider.blank? %>

<p>If you have any questions or need help please contact the Trunkit Team. Our email is <%= mail_to("Team@Trunkit.com") %>.</p>

<p>Thanks for joining and congrats on becoming a Trunkit member!</p>

<p>Sam, Max &amp; the Trunkit Team</p>

app/views/notifier/welcome_email.text.erb
HI <%= @user.first_name %>,

We’re so excited that you’ve signed up to become a member of Trunkit and we hope you had a great first experience using the site. Your favorite fashion boutiques can now work together to bring you the best customer experience while offering you additional inventory that you’ll love. <%= "In order to sign in again using the same account we need you to create a password by visiting the link below." if @user.provider.blank? %>

<%= settings_user_url if @user.provider.blank? %>

If you have any questions or need help please contact the Trunkit Team. Our email is Team@Trunkit.com.

Thanks for joining and congrats on becoming a Trunkit member!

Sam, Max & the Trunkit Team