config/routes.rb
Trunkit::Application.routes.draw do
  get 'learn_more/learn_trunkit'

  get 'learn_more/learn_trunksale'

  get 'learntrunksale/learntrunksale'

  get 'learn_trunkit/learn_trunkit'

  root to: "contents#index"

  # Catalog
  get "stream"                    => "stream#index",     as: :stream
  get "stream/following"          => "stream#following", as: :stream_following
  get "stream/category/:category" => "stream#index",     as: :stream_category

  resources :favorites, only: [:index, :create]

  resources :items do
    put 'support',   on: :member
    put 'unsupport', on: :member

    resources :declinations, only: [:index, :update], controller: "item_declinations"
    resources :notifications, only: [:create], controller: "item_notifications"

    resources :photos, controller: "item_photos" do
      put "reorder", on: :collection
    end
  end

  resources :brands, only: [:index, :create]
  resources :categories, only: [:index]
  resources :categories, only: [:index]

  resources :boutiques, :brands, only: [:show] do
    get 'search',   on: :collection
    put 'follow',   on: :member
    put 'unfollow', on: :member
  end

  # Product discovery
  resource :discover, controller: 'discover' do
    get 'q' => 'discover#create', as: :search
  end

  # Checkout and Shopping Cart
  resource :cart do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  namespace :checkout do
    resources :shipping_addresses do
      put "select", on: :member
    end

    resource :delivery_options, :payment_method, :order
  end

  # User information
  resource  :user, only: [:update] do
    get "settings"
  end

  resources :addresses

  # Boutique Management Interfaces
  resources :notifications, :customer_orders, only: [:index]
  resources :customer_orders
  

  scope("order_items/:id", as: :order_item) do
    resource :cancellation, only: [:new, :create], controller: "order_item_cancellations"
    put "complete" => "order_items#complete", as: :complete
  end

  # Boutique Transfers management
  namespace :payments do
    resource  :company, controller: "company"
  end

  # Session Management
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Administrative Interfaces
  resources :shipping_events, only: [:create]

  namespace :admin do
    resources :boutiques
    resources :brands, :categories, :customer_orders

    resources :items do
      put :approve, :unapprove, on: :member
      get :pending_approval,    on: :collection

      resources :sizes,  controller: "item_sizes"
      resources :photos, controller: "item_photos"
    end

    resources :users, except: [:show] do
      post "welcome"    => "users#welcome"
      put  "masquerade" => "users#masquerade"
    end
  end

  get "admin" => redirect("/admin/customer_orders")

  post "boutique_sign_up" => "boutique_sign_up#create"

  # Catch-all, generic routing
  get "*path" => "contents#show"
end

app/controllers/notifications_controller.rb
class NotificationsController < CatalogAbstractController
  def index
    @activities = Activity.for_notification_stream(current_user)
    current_user.touch(:last_viewed_notifications_at)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def render_notification(notification)
    return if notification.owner.blank?

    if current_user.parent.items.map(&:id).include?(notification.subject_id) && notification.subject_type == "Item" && notification.action == "support"
      render("item_supported", notification: notification)
    elsif notification.subject_type == "Item" && notification.action == "purchased"
      render("item_purchased", notification: notification)
    elsif notification.subject_type == "Boutique" && notification.action == "follow"
      render("boutique_follow", notification: notification)
    end
  end

  def notification_time_in_words(notification)
    to_time   = Time.now
    from_time = notification.created_at

    distance_in_minutes = ((to_time - from_time)/60.0).round
    distance_in_seconds = (to_time - from_time).round

    text = case distance_in_minutes
    when 0..1
      "#{distance_in_seconds}s"
    when 2...60
      "#{distance_in_minutes}m"
    when 60...1440
      "#{(distance_in_minutes / 60.0).round}h"
    when 1440...43200
      "#{(distance_in_minutes / 1440.0).round}d"
    else
      from_time.strftime("%m/%d/%Y")
    end

    content_tag(:span, text, class: "timestamp")
  end
end

app/views/notifications/_boutique_follow.html.erb
<%= content_tag(:div, class: "catalog-notification") do %>
  <%= content_tag(:div, image_tag(notification.owner.photo.url), class: "photo") %>
  <%= content_tag(:span, "#{notification.owner.name} is now following you", class: "message") %>
  <%= notification_time_in_words(notification) %>
<% end %>

app/views/notifications/_item_purchased.html.erb
<%= link_to(customer_orders_path(type: "supplied"), class: "catalog-notification") do %>
  <%= content_tag(:div, image_tag(notification.owner.photo.url), class: "photo") %>
  <%= content_tag(:span, "#{notification.owner.name} purchased #{notification.subject.name}", class: "message") %>
  <%= notification_time_in_words(notification) %>
<% end %>

app/views/notifications/_item_supported.html.erb
<%= link_to(boutique_path(notification.owner_id), class: "catalog-notification") do %>
  <%= content_tag(:div, image_tag(notification.owner.stream_photo.thumb), class: "photo") %>
  <%= content_tag(:span, "#{notification.owner.name} curated #{notification.subject.name}", class: "message") %>
  <%= notification_time_in_words(notification) %>
<% end %>

app/views/notifications/index.html.erb
<% @activities.each do |notification| %>
<%= render_notification(notification) %>
<% end %>