config/routes.rb
Trunkit::Application.routes.draw do
  get 'learn_more/learn_trunkit'

  get 'learn_more/learn_trunksale'

  get 'learntrunksale/learntrunksale'

  get 'learn_trunkit/learn_trunkit'

  root to: "contents#index"

  # Catalog
  get "stream"                    => "stream#index",     as: :stream
  get "stream/following"          => "stream#following", as: :stream_following
  get "stream/category/:category" => "stream#index",     as: :stream_category

  resources :favorites, only: [:index, :create]

  resources :items do
    put 'support',   on: :member
    put 'unsupport', on: :member

    resources :declinations, only: [:index, :update], controller: "item_declinations"
    resources :notifications, only: [:create], controller: "item_notifications"

    resources :photos, controller: "item_photos" do
      put "reorder", on: :collection
    end
  end

  resources :brands, only: [:index, :create]
  resources :categories, only: [:index]
  resources :categories, only: [:index]

  resources :boutiques, :brands, only: [:show] do
    get 'search',   on: :collection
    put 'follow',   on: :member
    put 'unfollow', on: :member
  end

  # Product discovery
  resource :discover, controller: 'discover' do
    get 'q' => 'discover#create', as: :search
  end

  # Checkout and Shopping Cart
  resource :cart do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  namespace :checkout do
    resources :shipping_addresses do
      put "select", on: :member
    end

    resource :delivery_options, :payment_method, :order
  end

  # User information
  resource  :user, only: [:update] do
    get "settings"
  end

  resources :addresses

  # Boutique Management Interfaces
  resources :notifications, :customer_orders, only: [:index]
  resources :customer_orders
  

  scope("order_items/:id", as: :order_item) do
    resource :cancellation, only: [:new, :create], controller: "order_item_cancellations"
    put "complete" => "order_items#complete", as: :complete
  end

  # Boutique Transfers management
  namespace :payments do
    resource  :company, controller: "company"
  end

  # Session Management
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Administrative Interfaces
  resources :shipping_events, only: [:create]

  namespace :admin do
    resources :boutiques
    resources :brands, :categories, :customer_orders

    resources :items do
      put :approve, :unapprove, on: :member
      get :pending_approval,    on: :collection

      resources :sizes,  controller: "item_sizes"
      resources :photos, controller: "item_photos"
    end

    resources :users, except: [:show] do
      post "welcome"    => "users#welcome"
      put  "masquerade" => "users#masquerade"
    end
  end

  get "admin" => redirect("/admin/customer_orders")

  post "boutique_sign_up" => "boutique_sign_up#create"

  # Catch-all, generic routing
  get "*path" => "contents#show"
end

app/controllers/checkout/delivery_options_controller.rb
class Checkout::DeliveryOptionsController < CatalogAbstractController
  force_ssl if: -> { Rails.env.production? }

  before_filter :verify_shopper_has_cart_items

  def show
  end

  def update
    current_cart.items.each do |ci|
      ci.update_attribute(:shipping_rate_id, params[:shipping_rates][ci.id.to_s])
    end

    redirect_to(checkout_payment_method_path)
  end
end

app/controllers/checkout/orders_controller.rb
class Checkout::OrdersController < CatalogAbstractController
  force_ssl if: -> { Rails.env.production? }

  before_filter do
    @changes = current_cart.verify_quantities!
  end

  before_filter :verify_shopper_has_cart_items
  before_filter do
    if current_cart.total_price_after_credit > 0
      begin
        @token = Stripe::Token.retrieve(session[:card_token])
      rescue Stripe::InvalidRequestError
        redirect_to(checkout_payment_method_path)
      end
    end
  end

  def show
  end

  def update
    current_cart.capture_order!(session[:card_token])
    session[:cart_id] = nil
  end
end

app/controllers/checkout/payment_methods_controller.rb
class Checkout::PaymentMethodsController < CatalogAbstractController
  force_ssl if: -> { Rails.env.production? }

  before_filter :verify_shopper_has_cart_items

  def show
    redirect_to(checkout_order_path) unless current_cart.total_price_after_credit > 0
  end

  def update
    session[:card_token] = params[:card_token]
    redirect_to(checkout_order_path)
  end
end

app/controllers/checkout/shipping_addresses_controller.rb
class Checkout::ShippingAddressesController < CatalogAbstractController
  force_ssl if: -> { Rails.env.production? }

  before_filter :verify_shopper_has_cart_items

  def index
    if current_user.addresses.blank?
      @address = current_user.addresses.build
      render("new")
    else
      render("index")
    end
  end

  def new
    @address = current_user.addresses.build
  end

  def create
    @address = current_user.addresses.create(address_params)

    if @address.persisted?
      render("index")
    else
      render("new")
    end
  end

  def edit
    @address = current_user.addresses.find(params[:id])
    render("new")
  end

  def update
    @address = current_user.addresses.find(params[:id])
    @address.update_attributes(address_params)
    render("index")
  end

  def destroy
    current_user.addresses.find(params[:id]).destroy
    render("index")
  end

  def select
    address = current_user.addresses.find(params[:id])
    current_cart.shipping_address = address
    current_cart.save

    redirect_to(checkout_delivery_options_path)
  end

private
  def address_params
    params.require(:address).permit([:street, :street2, :city, :state, :postal_code])
  end
end

app/controllers/orders_controller.rb
class OrdersController < CatalogAbstractController
  def index
    if current_user.parent_id.blank?
      @orders = Cart.where(user_id: current_user.id).ordered.includes(:user)

      render(action: "index_shopper")
    else
      @orders      = Cart.boutique_orders_listing(current_user, params)
      @users       = User.unscoped.find(@orders.map(&:user_id)).index_by(&:id)
      @commissions = Commission.collectable_for(current_user)

      render(action: "index_boutique")
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/checkout/delivery_options_helper.rb
module Checkout::DeliveryOptionsHelper
end

app/helpers/checkout/orders_helper.rb
module Checkout::OrdersHelper
end

app/helpers/checkout/payment_methods_helper.rb
module Checkout::PaymentMethodsHelper
end

app/helpers/checkout/shipping_addresses_helper.rb
module Checkout::ShippingAddressesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def listing_order_date(user, cart)
    items = cart.items.where(supplying_boutique_id: user.parent_id)
    return if items.blank?

    if items.all?{|i| (i.completed_at.present? && !i.refundable?) || i.refund_ledger_entry_id.present? }
      last_item = items.max(&:updated_at)
      time      = last_item.refunded? ? last_item.refund_ledger_entry.created_at : last_item.completed_at

      "Date Completed: #{time.strftime('%m/%d/%Y')}" if time
    else
      "Date Ordered: #{cart.captured_at.strftime('%m/%d/%Y')}"
    end
  end

  def item_order_status_button(user, cart_item)
    if cart_item.cancellation_refund_id.present?
      link_to("Cancelled", "#", class: "btn btn-supplied disabled")
    elsif cart_item.refund_ledger_entry_id.present?
      link_to("Refunded", "#", target: "_blank", class: "btn disabled")
    elsif cart_item.refund_requested.present?
      link_to("Refund Requested", "#", target: "_blank", class: "btn")
    elsif cart_item.completed_at.present? && user.parent_id.present?
      link_to("Shipping Label", cart_item.shipping_label.postage_label.label_url, target: "_blank", class: "btn shipping-label")
    elsif cart_item.supplied?(current_user.parent_id)
      link_to("Pending", "#cart-item-complete-#{cart_item.id}", class: "btn fancybox")
    elsif user.parent_id.present?
      link_to("Curated", "#", class: "btn btn-supplied disabled")
    elsif cart_item.delivered? && cart_item.refundable?
      link_to("Request Refund", "#", class: "btn btn-supplied")
    elsif cart_item.delivered? && !cart_item.refundable?
      link_to("Completed", "#", class: "btn btn-supplied")
    elsif cart_item.shipped?
      link_to("Shipped", "#", class: "btn btn-supplied disabled")
    else
      link_to("Pending", "#", class: "btn disabled")
    end
  end
end

app/views/checkout/orders/show.html.erb
<div class="checkout" id="checkout-confirm">
  <h1>Checkout</h1>

  <nav>
    <ul>
      <%= content_tag(:li, link_to("Shopping Cart", cart_path), class: "active") %>
      <%= content_tag(:li, link_to("Shipping Address", checkout_shipping_addresses_path), class: "active") %>
      <%= content_tag(:li, link_to("Delivery Options", checkout_delivery_options_path), class: "active") %>
      <%= content_tag(:li, link_to("Payment Method", checkout_payment_method_path), class: "active") %>
      <li class="active">Confirm Order</li>
    </ul>
  </nav>

  <%= content_tag(:p, "Due to a change in prices or availability, items in your cart have been updated.", class: "notitication error") if @changes.values.any?(&:present?) %>

  <h2>Please Review The Shipping and Payment Details</h2>

  <div class="order-details">
    <address>
      <h6>Shipping Address</h6>
      <%= current_cart.shipping_address.to_s.gsub("\n", "<br>").html_safe %><br>
      <%= link_to("Change", checkout_shipping_addresses_path) %>
    </address>

    <%= content_tag(:div, class: "payment-info") do %>
      <h6>Trunkit Credit</h6>
      <%= content_tag(:span, "Credit Balance: #{number_to_currency(-current_user.account_balance)}", class: "name") %>
    <% end if current_user.account_balance < 0 %>

    <%= content_tag(:div, class: "payment-info") do %>
      <h6>Credit/Debit Card Info</h6>
      <%= content_tag(:span, @token.card.name, class: "name") %>

      <span class="card-type">
        <%= content_tag(:em, @token.card.brand, class: @token.card.brand.downcase.gsub(/[^a-z]/, '-')) %>

        <span>
          ending in <%= @token.card.last4 %>
        </span>
      </span>

      <%= link_to("Change", checkout_payment_method_path) %>
    <% end if current_cart.total_price_after_credit > 0 %>
  </div>

  <div class="items">
    <header>
      <div class="name">Item(s)</div>
      <div class="unit">Item Price</div>
      <div class="delivery">Delivery</div>
      <div class="total">Total</div>
    </header>

    <% current_cart.items.each do |cart_item| %>
    <div class="wrapper">
      <div class="row">
        <div class="name">
          <%= image_tag(cart_item.item.primary_photo.url.thumb) %>

          <div>
            <%= content_tag(:span, cart_item.item.name) %>

            <ul>
              <%= content_tag(:li, "Size: #{cart_item.size}") if cart_item.size.present? %>
              <%= content_tag(:li, "Quantity: #{cart_item.quantity}") %>
            </ul>
          </div>
        </div>

        <%= content_tag(:div, number_to_currency(cart_item.unit_price), class: "unit") %>
        <%= content_tag(:div, number_to_currency(cart_item.shipping), class: "delivery") %>
        <%= content_tag(:div, number_to_currency(cart_item.subtotal_with_shipping), class: "total") %>
      </div>
    </div>
    <% end %>

    <footer>
      <%= content_tag(:div, "Taxes: #{number_to_currency(current_cart.tax)}", class: "tax") %>
      <%= content_tag(:div, "Total: #{number_to_currency(current_cart.total_price)}", class: "total") %>

      <% if current_user.account_balance < 0 %>
        <%= content_tag(:div, "Trunkit Credit: #{number_to_currency(-current_user.account_balance)}", class: "total") %>
        <%= content_tag(:div, "Total After Credit: #{number_to_currency(current_cart.total_price_after_credit)}", class: "total") %>
      <% end %>
    </footer>
  </div>

  <%= link_to("Place Order", "#confirm-barrier", class: "fancybox btn order place-order") %>
</div>

<div id="confirm-barrier">
  <h1>Confirm Purchase</h1>

  <p>All shipping and returns are handled directly by the boutique "supplier". The boutique that curated the item is NOT involved in the shipping or return process.</p>

  <p><%= link_to("Contact Us", "#") %> if you have any questions or concerns.</p>

  <%= link_to("Confirm", checkout_order_path, data: { method: :put, remote: true }, class: "btn order") %>
</div>

app/views/checkout/orders/update.js.erb
(function($) {
  $("a.place-order").
    removeClass("fancybox").
    addClass("gray completed").
    removeClass("place-order").
    attr("href", "#").
    text("Purchase Complete");

  var newBtn = $("<a></a>").prop("href", "/").addClass("btn order home").text("Continue Shopping");

  $("a.btn.completed").after(newBtn);

  $.fancybox.close();
})(jQuery);